[Feature] 엔티티, 리포지토리 세팅 #SCRUM-12
9oormthonUniv-seoultech/PROJECT_TEAM_APP_BE0 pull request #1
Opened 2024-09-11 10:25 UTC by chaeyoungeee

## ✅ 풀\_리퀘스트 체크리스트

- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

- 모든 엔티티 코드 추가
- 모든 리포지토리 코드 추가

<br/>

## 📎 변경한 이유

<br/>

## 👨🏻‍💻 테스트 체크리스트

<br/>

## 📌 변경 및 주의 사항

- 약관 동의 여부 저장해야할 것 같아서 멤버 엔티티에 boolean 타입으로 필드 추가했습니다. 
-> 시간으로 저장하는게 나을까요? 아니면 아예 저장할 필요가 없을까요?
- building_name, building_number 등이 길다고 생각되어 모두 앞의 이름을 제거하는 것(name, number)으로 통일했습니다.
-> 원래대로 길게 하는게 나을까요?

<br/>

2024-09-12 06:41 UTC, Hawardshin requested changes
- 약관 비동의시 가입이 불가하게 막아버리는 게 더 나을듯 해요! 그래서 따로 저장할 필요 없다고 생각합니다.
- 만약 building_name을 name으로 바꿀거라면 모든 네이밍 컨벤션을 building_id 이렇게 하지 않고 id 이렇게 했으면 좋겠습니다.
- 카멜케이스의 경우 디비에 따라서 다른 값이 저장되곤 하니까 명시적으로 @Colum(name=) 으로 지정해줬으면 좋겠습니다.

그 외의 코드들은 너무 깔끔하네요!! 코드 잘 봤습니다~~ 수정하고 알려주세요 바로 확인할께요!

2024-09-12 06:41 UTC, Hawardshin commented on src/main/java/com/groomiz/billage/member/entity/Member.java
> +    private Integer phoneNumber;
이거 String이 나을듯 합니다! 010 일때 저장이 10으로 될 수도 있고 추가적으로 나중에 +82) 이런식의 형식도 존재할 수 있을 것 같아요!

2024-09-12 09:30 UTC, Changha-dev commented
* 약관 이부분 찾아보니까 저희가 **서비스 이용약관**, **개인정보 처리방침** 두 가지만 필수로 받으면 될 것 같습니다.
 보통 다른 테이블로 빼거나 멤버테이블에서 필드로 관리하는 것 같은데 저희 서비스에서 약관이 막 변경될 일은 거의 없을 것 같아서 지금처럼 간단히 필드에 boolean값으로 추가하면 어떨까 싶습니다.
* 저도 하나로 통일하는게 괜찮은 것 같아요! 편한 방식으로 부탁드립니당

양 진짜 많은데 수고하셨습니다 엄청 잘하셨네요ㄷㄷ

2024-09-13 05:40 UTC, chaeyoungeee commented
말씀하신 부분들 수정했습니다 확인 부탁드릴게요! 😲

2024-09-13 17:39 UTC, Hawardshin approved these changes
LGTM!!
고생 많으셨습니다! 바로 머지해주셔도 될 것 같아요!

2024-09-14 00:13 UTC, merged

2024-09-14 05:42 UTC, orieasy1 commented
코멘트 늦어져서 죄송합니다ㅠㅠ
아침에 확인 해봤는데 체계적으로 잘 짜여진 것 같습니다! 저희 기능이랑 필요한 부분 빠짐없이 다 들어간 것 같아요!
양 엄청 많았는데 수고하셨습니다!