[Feature] 학교/예약 관련 응답 및 요청 생성 #SCRUM-18
9oormthonUniv-seoultech/PROJECT_TEAM_APP_BE0 pull request #4
Opened 2024-09-24 06:05 UTC by chaeyoungeee

## ✅ 풀\_리퀘스트 체크리스트

- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

 학교/예약 관련 응답 및 요청 생성하였습니다. 

<br/>

## 📎 변경한 이유

<br/>

## 👨🏻‍💻 테스트 체크리스트

해당 단과대에 소속된 모든 학과를 정상적으로 조회하는지 검증하는 테스트 추가했습니다.

<br/>

## 📌 변경 및 주의 사항

제가 작업한 api가 모두 학생 관련 api라서 @Tag 어노테이션 description option에 모두 [학생]이라고 붙여뒀는데 아래 사진처럼 swagger에서 아예 학생/관리자로 나눠서 그룹으로 만들면 어떨까요?

<img width="731" alt="image" src="https://github.com/user-attachments/assets/bf964981-8e22-4374-8fb7-98cb58117c72">

<br/>

2024-09-24 07:41 UTC, Changha-dev commented
네 그렇게 나누는 것 좋은것 같아요~~

2024-09-24 07:55 UTC, Changha-dev requested changes

2024-09-24 07:55 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/classroom/dto/response/ClassroomDetailResponse.java
> +	private String classroomImage;
여기 리스트로 바꿔야 될 것 같아요! 저희 이미지 여러개 받는거 맞죠??

2024-09-24 08:17 UTC, Changha-dev approved these changes

2024-09-25 09:53 UTC, orieasy1 commented
코드 확인했습니다!! 깔끔하게 잘 짜여진 것 같아요!!
수고 많으셨습니다!!

2024-09-26 06:45 UTC, Hawardshin approved these changes
스웨거에서 이렇게 나눌 수 있는건 몰랐네요~~ 
좋은 방법인 것 같습니다. 고생 많으셨습니다!

2024-09-26 06:53 UTC, merged