[Feature] 유저 관련 응답 및 요청 생성 #SCRUM-19
9oormthonUniv-seoultech/PROJECT_TEAM_APP_BE0 pull request #5
Opened 2024-09-26 04:01 UTC by Changha-dev

## ✅ 풀\_리퀘스트 체크리스트

- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

유저 관련 DTO와 Controller를 추가하였습니다. 
- UserController와 MemberController를 분리하였습니다.
- 비밀번호 수정 DTO에서 oldPassword, newPassword를 받도록 하였습니다. 
- 전화번호 수정 DTO에서 이메일도 함께 받도록 하였습니다. 
- 학번을 아이디로 받으므로 관련 JWT 코드를 알맞게 수정하였습니다. 

<br/>

## 📎 변경한 이유

- auth패키지가 따로 있으므로 이 안의 UserController는 회원 인증/인가 (로그인, 회원가입..) 부분을 관리하도록 하였고
그 외의 회원 로직은 MemberController에서 관리하도록 하였습니다. 
<br/>

## 👨🏻‍💻 테스트 체크리스트

- AuthControllerTest를 학번을 아이디로 수정하여 테스트하였습니다.

<br/>

## 📌 변경 및 주의 사항

<br/>

2024-09-26 07:07 UTC, chaeyoungeee requested changes
코드 확인했습니다 수고하셨습니다 👍👍!!

2024-09-26 07:07 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/member/dto/MemberInfoResponse.java
> +	private String major;
type Enum(Major)으로 변경하는게 좋을 것 같습니다

2024-09-27 05:32 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/member/dto/MemberInfoResponse.java
> +	private String major;
넵 변경하였습니다!

2024-09-28 00:54 UTC, chaeyoungeee approved these changes

2024-09-28 00:54 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/member/dto/MemberInfoResponse.java
> +	private String college;
잘못된 값 들어왔을 때 체크할 수 있게 type을 Enum으로 변경하는게 좋을 것 같습니다~!!

2024-09-28 00:55 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/member/dto/MemberInfoResponse.java
> +	private String major;
확인했습니다 
머지하시면 될 거 같아요 수고하셨습니다~! 👍

2024-09-28 02:34 UTC, merged