[Feature] 관리자 관련 응답 및 요청 생성 #SCRUM-20
9oormthonUniv-seoultech/PROJECT_TEAM_APP_BE0 pull request #7
Opened 2024-09-26 22:58 UTC by orieasy1

✅ 풀_리퀘스트 체크리스트
- [x] PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- [x] commit message 가 적절한지 확인해주세요.
- [x] 적절한 branch 로 요청했는지 확인해주세요.
- [x] Assignees, Label 을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

🔄 변경 사항
관리자 관련 응답 및 요청 생성하였습니다.

📎 변경한 이유

👨🏻‍💻 테스트 체크리스트

📌 변경 및 주의 사항
@tag 어노테이션 사용해서 [관리자]로 붙여두었습니다.
관리자의 경우 강의실 관련 필터링과 조회 모두 예약 목록을 기반으로 해서 classroom패키지와 reservation 패키지 두 군데에서 공통되는 부분이 많다고 느꼈습니다. 이러한 부분을 묶어 좀 더 효율적인 코드를 구현해보려 했으나 묶으면 묶을 수록 코드가 더 더러워지는 것 같아서 notion의 응답 요청 값에 맞추어 코드를 짰습니다.
특히 classroom 패키지의 파트에 이런 고민이 많았어서 어떻게 생각하시는지에 대해 듣고 싶습니다.
특히 강의실 현황 필터링 파트에서 List로 묶이는 부분 때문에 지금과 같이 코드를 짰는데 이 파트가 제일 고민이 많았어서 현재 코드에 대해 어떻게 생각하는지 듣고 싶습니다.

2024-09-28 02:57 UTC, Changha-dev commented
코드 확인하였습니다~! 수고하셨어요 👍
변경할 부분들 코멘트 달아놨습니다

2024-09-29 06:53 UTC, Changha-dev requested changes

2024-09-29 06:53 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomStatusResponse.java
> +class ClassroomResponse {
headcount(인원 수) 도 추가해야 될 것 같아요!
확인해보니까 노션에는 없는데 피그마에는 추가됐네요

2024-09-29 06:53 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/reservation/controller/AdminReservationController.java
> +	public String getReservation(@PathVariable Long reservationId) {
여기에도 Operation추가 부탁드립니다~!

2024-09-29 06:53 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomDetailResponse.java
> +
아 여기도 Integer로 바꿔야 될 것 같아요!
노션에는 String을 Integer로 안바꿨네요..ㅎ

2024-09-29 06:53 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomDetailResponse.java
> +		private String studentId;
Integer로 변경 부탁드립니다!

2024-09-29 06:53 UTC, Changha-dev commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomStatusResponse.java
> +}
이 부분은 채영이가 한 reservationTime DTO랑 겹치니까 나중에 하나로 통일해도 될 것 같다

2024-09-29 13:15 UTC, chaeyoungeee requested changes
확인 늦어서 죄송합니다 수고하셨습니다! 저도 지금 방법 좋은 거 같아요
type들 설계한 거에 맞춰서 int -> Integer, 그리고 date는 String -> LocalDate로 수정해주시면 좋을 거 같습니다 제가 적어놓은거 외에도 많아서 하나하나 달기 애매해서 확인하시고 수정 부탁드립니다 😊

2024-09-29 13:15 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationStatusListResponse.java
> +		private String date;
type LocalDate로 변경하는게 좋을 거 같습니다

2024-09-29 13:15 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationResponse.java
> +	private String purpose;
예약 목적 타입 체크되게 ReservationPurpose Enum으로 type 변경하면 좋을 거 같아요

2024-09-29 13:15 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationResponse.java
> +	private int startTime;
startTime이랑 endTime도 type이 다 Integer로 되어 있어서 하나로 맞추는게 나을 거 같아요 Integer로 변경 부탁드립니다!

2024-09-29 13:15 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomStatusResponse.java
> +}
지원님 편하신대로 어떻게할지 정해주시면 제가 수정하겠습니다

2024-09-29 13:15 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/classroom/dto/request/AdminClassroomStatusRequest.java
> +	private List<Long> buildings;
생각해봤는데 우리 어드민이 자신이 관리하는 건물 정보 이미 가지고 있는데 이거 필요할까요?

2024-09-29 13:15 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/classroom/dto/request/AdminClassroomStatusRequest.java
> +	private List<Integer> floors;
피그마 보니까 층 필터링하는 부분 없어진 거 같아요
<img width="317" alt="image" src="https://github.com/user-attachments/assets/404b5b35-c911-4931-9b9e-dee00e551a14">

2024-09-30 02:01 UTC, Hawardshin requested changes
컨트롤러에서 ResponseEntity 를 만드는 걸 추천합니당

2024-09-30 02:01 UTC, Hawardshin commented on src/main/java/com/groomiz/billage/classroom/dto/request/AdminClassroomDetailRequest.java
request Dto에는 해주면 좋을듯 합니다! 다른 곳에도 적용해주시면 좋을듯 해요!
- 필수 값에 @NotNull 추가
- 리스트나 문자열의 길이를 검증하는 @Size 추가
- 특정 형식을 요구하는 경우 @Pattern 사용

2024-09-30 02:01 UTC, Hawardshin commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationStatusListResponse.java
> +		private String date;
동의합니다

2024-09-30 02:01 UTC, Hawardshin commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationStatusListResponse.java
> +		private String date;
대신 저장할 때 제가 알기론 localDate가 Long 값으로 바꿔서 저장하는 걸로 알아요.
 Jackson의 @JsonFormat 어노테이션을 사용하여 날짜 형식을 지정 해주면 좋을듯해요!

2024-09-30 02:01 UTC, Hawardshin commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomDetailResponse.java
> +
시작시간 끝 시간을 다음과 같이 하는 건 어떨까요?
@Schema(description = "시작 시간", example = "09:00")
private LocalTime startTime;

@Schema(description = "종료 시간", example = "10:00")
private LocalTime endTime;

2024-09-30 02:01 UTC, Hawardshin commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationResponse.java
> +	private String purpose;
public enum ReservationPurpose {
    STUDY, LECTURE, MEETING;
}

이런식으로? 하면 좋을듯하네용

2024-09-30 02:06 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/reservation/dto/response/AdminReservationResponse.java
> +	private String purpose;
이거 저번에 도메인 세팅할 때 만들어서놔서 그거 사용하시면 될 거 같아요!

2024-09-30 06:31 UTC, chaeyoungeee commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomDetailResponse.java
> +
전 LocalTime으로 변경하는 거 좋은 거 같습니다

2024-09-30 09:36 UTC, orieasy1 commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomStatusResponse.java
> +}
제가 reservation time으로 통일시키도록할게요!!

2024-09-30 10:04 UTC, orieasy1 commented on src/main/java/com/groomiz/billage/classroom/dto/request/AdminClassroomStatusRequest.java
> +	private List<Integer> floors;
앗 감사합니다! 관련 부분 의견 빠르게 듣고자 카톡 보내놓았습니다!

2024-09-30 10:14 UTC, orieasy1 commented on src/main/java/com/groomiz/billage/classroom/dto/request/AdminClassroomStatusRequest.java
> +	private List<Long> buildings;
이거는 필터링 요청이 들어왔을 때 요청한 부분에 대한 리스트를 의미한 거긴 합니다!!  현황을 보여줄 특정 건물 리스트인거죠!!  근데 UI보고 다시 수정해야할 것 같아요!

2024-09-30 10:18 UTC, orieasy1 commented on src/main/java/com/groomiz/billage/classroom/dto/response/AdminClassroomDetailResponse.java
> +
LocalTime으로 통일하겠습니다.

2024-09-30 12:02 UTC, orieasy1 commented
1. ReservationType  enum 만들었는데 확인 부탁드려요

2.  @JsonFormat 적용하고 싶다해서 적용했는데 shape을 number로 할지 string으로 할지 논의 필요 (현재는 아래처럼 string으로 해둠)
    * @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    * @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm") <br>
이대로 한다면 시간을 HH:mm으로 할 지 HH:mm:ss로 할 지 논의 필요

3. AdminReservationRequest에 시작날짜, 종료날짜에 다 notnull을 달아두기는 했는데 일반 타입의 경우 해당 날짜에 대한 예약을 받는 거기 때문에 종료날짜를 어떻게 할지에 대한 의논이 필요할 것 같습니다.

2024-09-30 13:49 UTC, Changha-dev commented
정말 수고하셨습니다..!
ReservationType 확인했고 
HH:mm까지만 하는게 좋을 것 같아요 ss까지는 필요없을 것 같아서 
어드민에서 일반 타입일 경우 종료날짜도 시작날짜와 똑같이 받으면 될 것 같은데 어떤가요?

2024-10-01 08:21 UTC, Hawardshin approved these changes
저도 확인했습니다. ss까지 할 필요는 없어보여요!!

2024-10-01 10:13 UTC, Changha-dev approved these changes

2024-10-01 10:13 UTC, chaeyoungeee approved these changes

2024-10-01 10:14 UTC, merged